### ISSUE TITLE
Connection error line 4

### ISSUE THREAD

**Issue by CalyGit** [coderacheal/database-connection-config#1]
InterfaceError: ('28000', "[28000] [Microsoft][ODBC SQL Server Driver][SQL Server]Login failed for user 'dapDB'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC SQL Server Driver][SQL Server]Login failed for user 'dapDB'. (18456)")

**Comment by coderacheal** [comment]
@CalyGit it seems you set the user as dapDB. The user is dataAnalyst_LP2 and dapDB is the database not the user. Please check this in your code

**Comment by CalyGit** [comment]
> @CalyGit it seems you set the user as dapDB. The user is dataAnalyst_LP2 and dapDB is the database not the user. Please check this in your code

This is it. Thanks @coderacheal
